version: '3.3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app       # to oznacza ze zmiana w biezacym katalogu bedzie zmiana w /app kontenera
    depends_on:
      - db


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: admin
      POSTGRES_PASSWORD: root

    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 55432:5432


